### ISSUE TITLE
Fonts and music art on lockscreen

### ISSUE THREAD

**Issue by 3abdooo** [siavash79/AOSPMods#72] opened 2022-04-19 03:17 UTC
cannot apply fonts ant music art on lockscreen
on the last canary 010 release
even if i did restart my device more than 2 times

 - Device: samsung s7 (herolte)
 - OS: lineageOS 19.1 with micrg

**Comment by siavash79** [comment] 2022-04-19 03:43
It's possible that lineageos doesn't have the music backdrop system on it

Will look into the fonts issue soon

**Comment by siavash79** [comment] 2022-04-19 03:45
It's possible that lineageos doesn't have the music backdrop system on it

Will look into the fonts issue soon

**Comment by siavash79** [comment] 2022-04-19 12:58
fixed on a3fbab086b6295e00419036572109061d2452a74

**Closed** 2022-04-20 08:19 UTC
Labels: wontfix, fixed

**Comment by 3abdooo** [comment] 2022-04-20 09:06
@siavash79 an other thing i don't know if it is a bug or it is supposed to be like that.
the font changes are not system wide
the only font that change is (app name, QS Tile, settings)
no home screen clock, no in apps fonts, no keyboard font, etc

**Comment by siavash79** [comment] 2022-04-20 13:48
It's not a bug
The fonts that change are system fonts. other fonts are related to app and are not supposed to change

You can only force Google sans font to apply to the whole system
