### ISSUE TITLE
[Bug] Status bar clock wrong position & operator not showing on lockscreen

### ISSUE THREAD

**Issue by diegonogaretti** [siavash79/AOSPMods#512] opened 2023-01-02 09:50 UTC
### Describe the issue

Status bar clock (default position setting) is in the same position as when set to show above notifications. Occasionally operator text on lockscreen disappears.

### Steps to reproduce

1. Just updated to the latest canary and have this bug from the first boot.
2. Previous canary triggered this bug when changing between dark and light theme.

### Expected bahavior

Status bar clock should be in the default position and operator should be shown on lockscreen

### Your device setup (Please take some time to give correct information here)

- Google Pixel 6
- Android 13 stable, stock, last available factory image
- Dec security update
- Magisk 25.2
- Adaway, AOSP Mods, Pixel Launcher, De-Bloater, Lawnchair, ReVanced Manager, Solid Explorer, [SharedUID] System UI
- AOSP Mods (Full version) last canary version, De-Bloater 1.0, mindetach 2.3, Systemless Hosts 1.0, Universal SafetyNet Fix 2.3.1, Zygisk - LSPosed 1.8.5
- LSPosed 1.8.5
- AOSP Mods (Full version) last canary version

**Comment by EleoXDA** [comment] 2023-01-02 17:29
I am also on pixel 6 Dec security patch. Please share your AOSPMods settings:

To get AOSPMods settings, go to "3dot menu->import/export->export settings to a file" and save it to a file. Then add that file into a zipped folder and upload it in a new GitHub message here.

**Comment by Jnss98b** [comment] 2023-01-03 01:14
I have this issue too on my pixel 7 pro on the dec patch running aospmods canary 200 even though this was supposed to be fixed in 194 or something. This usually happens after either startup or after switching device theme (especially as a result of battery saving mode)

**Comment by EleoXDA** [comment] 2023-01-03 07:46
> I have this issue too on my pixel 7 pro on the dec patch running aospmods canary 200 even though this was supposed to be fixed in 194 or something. This usually happens after either startup or after switching device theme (especially as a result of battery saving mode)

"Usually" means non-reproducible

**Comment by diegonogaretti** [comment] 2023-01-03 09:04
> I am also on pixel 6 Dec security patch. Please share your AOSPMods settings:
> 
> To get AOSPMods settings, go to "3dot menu->import/export->export settings to a file" and save it to a file. Then add that file into a zipped folder and upload it in a new GitHub message here.

Here you go
[AOSPMods_settings.zip](https://github.com/siavash79/AOSPMods/files/10335295/AOSPMods_settings.zip)

**Comment by diegonogaretti** [comment] 2023-01-03 09:08
> > I have this issue too on my pixel 7 pro on the dec patch running aospmods canary 200 even though this was supposed to be fixed in 194 or something. This usually happens after either startup or after switching device theme (especially as a result of battery saving mode)
> 
> "Usually" means non-reproducible

Can confirm all that he says. After first boot or when changing theme (this always trigger it for me).
Don't know if operator text on lockscreen is related to this but setting it to a fixed text (I put the operator name) doesn't disappear anymore.

**Comment by diegonogaretti** [comment] 2023-01-03 13:39
@EleoXDA I would like to say that everything was good to canary-193 at least (the one which solved light theme bugs). These issues started to appear from 194.

**Comment by EleoXDA** [comment] 2023-01-03 13:45
Fix was done according to user reports. So it means something went wrong in Dec patch that broke it and thus there was a fix

**Comment by diegonogaretti** [comment] 2023-01-03 13:49
> Fix was done according to user reports. So it means something went wrong in Dec patch that broke it and thus there was a fix

Was on dec patch too with the 193 and no issues at all, started after that version. Just my idea.

**Comment by EleoXDA** [comment] 2023-01-03 14:32
> > Fix was done according to user reports. So it means something went wrong in Dec patch that broke it and thus there was a fix
> 
> Was on dec patch too with the 193 and no issues at all, started after that version. Just my idea. EDIT: Is there a way to download a previous version?

Of course you can. Go to the version update commit and find the two links. You can also find all the canary versions of AOSPMods in telegram channel. We also do have telegram support group.

**Comment by diegonogaretti** [comment] 2023-01-03 14:45
> > > Fix was done according to user reports. So it means something went wrong in Dec patch that broke it and thus there was a fix
> > 
> > 
> > Was on dec patch too with the 193 and no issues at all, started after that version. Just my idea. EDIT: Is there a way to download a previous version?
> 
> Of course you can. Go to the version update commit and find the two links. You can also find all the canary versions of AOSPMods in telegram channel. We also do have telegram support group.

Thanks! Will join it asap.
Just a question: how do I install an older version of the module? Just flashing in magisk or do I have to uninstall it first?

**Comment by EleoXDA** [comment] 2023-01-03 15:18
> > > > Fix was done according to user reports. So it means something went wrong in Dec patch that broke it and thus there was a fix
> > > 
> > > 
> > > Was on dec patch too with the 193 and no issues at all, started after that version. Just my idea. EDIT: Is there a way to download a previous version?
> > 
> > 
> > Of course you can. Go to the version update commit and find the two links. You can also find all the canary versions of AOSPMods in telegram channel. We also do have telegram support group.
> 
> Thanks! Will join it asap. Just a question: how do I install an older version of the module? Just flashing in magisk or do I have to uninstall it first?

just flash over it

**Comment by diegonogaretti** [comment] 2023-01-03 16:14
> > > > > Fix was done according to user reports. So it means something went wrong in Dec patch that broke it and thus there was a fix
> > > > 
> > > > 
> > > > Was on dec patch too with the 193 and no issues at all, started after that version. Just my idea. EDIT: Is there a way to download a previous version?
> > > 
> > > 
> > > Of course you can. Go to the version update commit and find the two links. You can also find all the canary versions of AOSPMods in telegram channel. We also do have telegram support group.
> > 
> > 
> > Thanks! Will join it asap. Just a question: how do I install an older version of the module? Just flashing in magisk or do I have to uninstall it first?
> 
> just flash over it

Just flashed and can confirm I no longer have bugged status bar clock and/or lockscreen operator moving/disappearing when changing between light and dark theme and vice versa

**Comment by Jnss98b** [comment] 2023-01-03 16:58
> "Usually" means non-reproducible

No need to be semantic. I said "usually" because sometimes systemui crashes in the process and that fixes it (restarting systemui is how the bug can be alleviate right now). A surefire way of triggering it for me is to turn on battery saver and then turn it off. That'll kickstart the bug everytime. Sometimes it even shows up right after battery saver is on

**Comment by EleoXDA** [comment] 2023-01-07 19:06
> > "Usually" means non-reproducible
> 
> No need to be semantic. I said "usually" because sometimes systemui crashes in the process and that fixes it (restarting systemui is how the bug can be alleviate right now). A surefire way of triggering it for me is to turn on battery saver and then turn it off. That'll kickstart the bug everytime. Sometimes it even shows up right after battery saver is on

When there us systemUI FC there is always logs. A true android user knows that FC, ANR and and WTF logs are stored in data/system/dropbox, and shares the mentioned logs in posts instead of saying it. 

So whether it is FC or you misspoke I can't "semantically" judge

**Closed** 2023-01-13 13:25 UTC
