### ISSUE TITLE
[Bug] Back gesture height settings conflict with each other

### ISSUE THREAD

**Issue by blackwind** [siavash79/AOSPMods#547] opened 2023-03-14 08:02 UTC
### Describe the issue

I want my back gesture to activate only within the bottom 10% of the screen when swiped from the left and only the bottom 50% of the screen when swiped from the right. I configured these settings in AOSPMods, but the 50% height applies to both sides.

### Steps to reproduce

* Go to Navigation bar > Gesture navigation
* Enable both back gesture settings
* Set their gesture heights to different numbers
* Observe that, although the side with the smaller gesture height only pops up the back symbol (<) within its configured range, it still navigates back if you swipe within the larger gesture's range

### Expected bahavior

Settings should be able to coexist.

### Your device setup (Please take some time to give correct information here)

* Google Pixel 7 Pro
* Android 13
* Feb 2023 update
* Magisk 25206
* LSPosed 1.8.6

**Comment by EleoXDA** [comment] 2023-03-14 13:53
https://user-images.githubusercontent.com/27622683/225022935-05f23d0b-a5cb-4601-a33a-50b09d2108ec.mp4

Can't reproduce.

**Comment by blackwind** [comment] 2023-03-14 17:00
https://user-images.githubusercontent.com/889881/225080929-cb87b18c-f5ff-4bce-8672-e56c931ce1d3.mp4

Requires a longer swipe than you were doing.

**Comment by EleoXDA** [comment] 2023-03-15 07:06
> https://user-images.githubusercontent.com/889881/225080929-cb87b18c-f5ff-4bce-8672-e56c931ce1d3.mp4
> 
> Requires a longer swipe than you were doing.

Something is wrong in your case. I went from one side to another and it ONLY triggered where I chose. See my screenrecord:
https://user-images.githubusercontent.com/27622683/225232548-b8bf843d-8df2-4a38-bff1-75061cfd191c.mp4

**Comment by EleoXDA** [comment] 2023-03-15 07:26
> https://user-images.githubusercontent.com/889881/225080929-cb87b18c-f5ff-4bce-8672-e56c931ce1d3.mp4
> 
> Requires a longer swipe than you were doing.

Please provide a bugreport as requested. You can create a new bugreport and see what we request to see and fill in your answers. I think there is something else that is hindering AOSPMods.

**Comment by siavash79** [comment] 2023-03-16 03:32
checkout the latest canary @blackwind

**Comment by blackwind** [comment] 2023-03-16 03:41
Can't reproduce anymore, cheers!

**Comment by blackwind** [comment] 2023-03-16 18:14
Related issue:

https://user-images.githubusercontent.com/889881/225714116-f76112d8-9ab8-450e-879e-f2d15cb7b7e5.mp4

**Comment by siavash79** [comment] 2023-03-17 06:53
Can't reproduce

**Comment by EleoXDA** [comment] 2023-03-17 14:01
> Related issue:
> 
> https://user-images.githubusercontent.com/889881/225714116-f76112d8-9ab8-450e-879e-f2d15cb7b7e5.mp4

Can't reproduce 

https://user-images.githubusercontent.com/27622683/225926739-2dc1b82e-7b62-4683-914c-6e15b3863dbc.mp4

**Comment by blackwind** [comment] 2023-03-17 14:32
I'm able to reproduce with the exact same settings you used. This is in canary-229:

https://user-images.githubusercontent.com/889881/225933511-b136ec41-1179-46c2-9da6-5cb96c712df1.mp4

**Comment by EleoXDA** [comment] 2023-03-17 16:33
> I'm able to reproduce with the exact same settings you used. This is in canary-229:
> 
> https://user-images.githubusercontent.com/889881/225933511-b136ec41-1179-46c2-9da6-5cb96c712df1.mp4
> 
> 

I am also on canary-229. Since we can't reproduce it means there is something wrong in your setup. You haven't provided all what we ask from bugreport. Please provide all info

**Comment by EleoXDA** [comment] 2023-03-19 15:46
I am guessing you do not want to provide logs as requested for bugreport. I will close this until we have more information. But, we can no longer reproduce the bug

**Closed by EleoXDA** 2023-03-19 15:46 UTC
