### ISSUE TITLE
White icon on brightness slider in QQS and dark in QS

### ISSUE THREAD

**Issue by bzz11g** [siavash79/AOSPMods#192] opened 2022-05-30 06:33 UTC
**Describe the bug**
The icon on the brightness slider is white when the QS is half open

**To Reproduce**
1. Go to 'Quick Settings Panel'
2. Activate 'Show brightness slider on QQS Panel', 'Move brightness slider to the bottom', 'Use a thick track on brightness slider'
3. Open QQS
4. See white icon
5. Open QS and icon changed to dark

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/1549909/170930896-352a5cf9-2e74-4390-b94a-89ac53f4dcb3.png)

 - Device: Google Pixel 6 
 - OS: 12 (SP2A.220505.002)

**Comment by EleoXDA** [comment] 2022-05-31 04:40
Duplicate of https://github.com/siavash79/AOSPMods/issues/56

**Comment by EleoXDA** [comment] 2022-06-02 05:43
Ok. So this happens only if you disable the light qs panel during the light theme option and use the light theme and not the dark theme.

In any other case there is no issue with the brightness icon. Right?

**Comment by bzz11g** [comment] 2022-06-02 06:13
> It is solely dependent on disabling the "light qs panel on light theme" option and using light theme.

Yes, I just test and you totally right

Also I find out that in QQS no gray background, You can see it in the screenshot in the first post.
If I express myself not quite clearly (English is not my native language) marked what I'm talking about with a blue checkmark
![image](https://user-images.githubusercontent.com/1549909/171564512-f7b163a1-3380-4bde-8c38-93c8a4516ba7.png)

**Comment by EleoXDA** [comment] 2022-06-02 06:22
> Now I'm on canary-31 build of AOSP mods There is no proplem with Light theme
Current stable 1.1.1 update is the newest update (after canary-31). What do you mean there is no problem with Light theme?

**Comment by bzz11g** [comment] 2022-06-02 06:34
I just update to stable 1.1.1
Dark QS theme with Light system theme
![Screenshot_20220602-093018](https://user-images.githubusercontent.com/1549909/171567766-6e6c2297-ed5e-4abd-9799-003c3c55887b.png)
Light QS theme with Light system theme
![Screenshot_20220602-092722](https://user-images.githubusercontent.com/1549909/171567846-1ae845f9-eaa1-4a26-9882-6829733edbe3.png)

**Comment by EleoXDA** [comment] 2022-06-02 06:35
Yes, I can reproduce it on my device as well.

**Comment by EleoXDA** [comment] 2022-06-19 17:23
Fixed

**Closed by EleoXDA** 2022-06-19 17:23 UTC
Labels: bug

**Comment by bzz11g** [comment] 2022-07-07 09:59
This bug is comeback 
White Icon on Light theme
White Icon on Dark theme
AOSPMods: Canary-70
Device: Pixel 6
OS: Stock 12.1.0 (SQ3A.220705.003, Jul 2022)
![Screenshot_20220707-125553](https://user-images.githubusercontent.com/1549909/177747079-bfcc9edb-1032-4219-90d5-c19e6c5c9521.png)![Screenshot_20220707-125559](https://user-images.githubusercontent.com/1549909/177747085-cff13dab-e7f0-4539-a5b1-f5410bd430b9.png)
