### ISSUE TITLE
[Bug] Light theme is not working

### ISSUE THREAD

**Issue by akmsk1999** [siavash79/AOSPMods#492] opened 2022-12-18 02:06 UTC
### Describe the issue

1.Apply light QS Panel when using light theme  2.Enable dual tone Panel

### Steps to reproduce

![Screenshot_20221218-000530_AOSP_Mods](https://user-images.githubusercontent.com/16622098/208276065-fe9bdf45-a55c-443f-ab6d-e5600bd5b0de.png)
![Screenshot_20221218-000517_AOSP_Mods](https://user-images.githubusercontent.com/16622098/208276068-7a0efd6b-439a-4984-9ce0-45af8b57ce0c.png)

### Your device setup (Please take some time to give correct information here)

December patch

### Logs

.... These two options are not working anymore 
I know you guys are busy with major bugfixing...
But please dont forget these two minor option plz
Many of us loves the white theme.....AOSPMODS is the only way to make it work...
This is a humble request... Plz Don't forget about fixing this option....sir

**Comment by EleoXDA** [comment] 2022-12-18 09:58
Duplicate of https://github.com/siavash79/AOSPMods/issues/482

Add it to that post instead

**Comment by akmsk1999** [comment] 2022-12-18 10:23
sir,remove dual tone QS option if u wish

But Sir, in Light theme QS tiles become pale....than accent...that looks weird....brightness slider and tiles should have same color....but tiles colors are pale than brightness sliders....it looks weird..... Plz sir do fix this....
![Screenshot_20221218-162056_Messenger](https://user-images.githubusercontent.com/16622098/208293067-13b69eb5-8c96-4657-93c6-62702d50e5a2.png)
![Screenshot_20221218-162132_Messenger](https://user-images.githubusercontent.com/16622098/208293071-a77cda17-c5c4-4bb2-98c7-2e7c4afe084a.png)

**Comment by EleoXDA** [comment] 2022-12-18 10:47
> sir,remove dual tone QS option if u wish
> 
> But Sir, in Light theme QS tiles become pale....than accent...that looks weird....brightness slider and tiles should have same color....but tiles colors are pale than brightness sliders....it looks weird..... Plz sir do fix this.... ![Screenshot_20221218-162056_Messenger](https://user-images.githubusercontent.com/16622098/208293067-13b69eb5-8c96-4657-93c6-62702d50e5a2.png) ![Screenshot_20221218-162132_Messenger](https://user-images.githubusercontent.com/16622098/208293071-a77cda17-c5c4-4bb2-98c7-2e7c4afe084a.png)

As I wrote above, theming is currently the last thing we are interested. And again, as I said you can add your report to the mentioned link: https://github.com/siavash79/AOSPMods/issues/482

And we will check if and when we have time.

**Comment by akmsk1999** [comment] 2022-12-18 11:04
thank you sir.....added it....humble request.. Plz Fix it when u guys have time

**Closed** 2022-12-24 10:55 UTC
