### ISSUE TITLE
[Bug] log spam with: Failed to open APK

### ISSUE THREAD

**Issue by huajijam** [siavash79/AOSPMods#556] opened 2023-03-24 15:34 UTC
### Describe the issue

A log spam by com.google.android.gms.perisitent

### Steps to reproduce

enable some function and get log spam

### Expected bahavior

no log spam

### Your device setup (Please take some time to give correct information here)

Pixel 7 Pro(Stock TQ2A.230305.008.C1)
Android 13
Magisk v25.2
using full Canary version of mod

### Logs

2023-03-24 23:30:01.244 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_DualToneQSSystem/AOSPModsDualToneQSSystem.apk': I/O error
2023-03-24 23:30:01.245 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_AndroidOverlayRemoveNavBar/AndroidOverlayRemoveNavBar.apk': I/O error
2023-03-24 23:30:01.246 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_DualToneQSSystem/AOSPModsDualToneQSSystem.apk': I/O error
2023-03-24 23:30:01.246 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_AndroidOverlayRemoveNavBar/AndroidOverlayRemoveNavBar.apk': I/O error
2023-03-24 23:30:01.247 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_DualToneQSSystem/AOSPModsDualToneQSSystem.apk': I/O error
2023-03-24 23:30:01.247 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_AndroidOverlayRemoveNavBar/AndroidOverlayRemoveNavBar.apk': I/O error
2023-03-24 23:30:01.249 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_DualToneQSSystem/AOSPModsDualToneQSSystem.apk': I/O error
2023-03-24 23:30:01.249 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_AndroidOverlayRemoveNavBar/AndroidOverlayRemoveNavBar.apk': I/O error
2023-03-24 23:30:01.250 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_DualToneQSSystem/AOSPModsDualToneQSSystem.apk': I/O error
2023-03-24 23:30:01.250 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_AndroidOverlayRemoveNavBar/AndroidOverlayRemoveNavBar.apk': I/O error
2023-03-24 23:30:01.251 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_DualToneQSSystem/AOSPModsDualToneQSSystem.apk': I/O error
2023-03-24 23:30:01.251 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_AndroidOverlayRemoveNavBar/AndroidOverlayRemoveNavBar.apk': I/O error
2023-03-24 23:30:01.252 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_DualToneQSSystem/AOSPModsDualToneQSSystem.apk': I/O error
2023-03-24 23:30:01.252 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_AndroidOverlayRemoveNavBar/AndroidOverlayRemoveNavBar.apk': I/O error
2023-03-24 23:30:01.253 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_DualToneQSSystem/AOSPModsDualToneQSSystem.apk': I/O error
2023-03-24 23:30:01.254 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_AndroidOverlayRemoveNavBar/AndroidOverlayRemoveNavBar.apk': I/O error
2023-03-24 23:30:01.254 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_DualToneQSSystem/AOSPModsDualToneQSSystem.apk': I/O error
2023-03-24 23:30:01.254 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_AndroidOverlayRemoveNavBar/AndroidOverlayRemoveNavBar.apk': I/O error
2023-03-24 23:30:01.256 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_DualToneQSSystem/AOSPModsDualToneQSSystem.apk': I/O error
2023-03-24 23:30:01.256 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_AndroidOverlayRemoveNavBar/AndroidOverlayRemoveNavBar.apk': I/O error
2023-03-24 23:30:01.257 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_DualToneQSSystem/AOSPModsDualToneQSSystem.apk': I/O error
2023-03-24 23:30:01.257 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_AndroidOverlayRemoveNavBar/AndroidOverlayRemoveNavBar.apk': I/O error
2023-03-24 23:30:01.258 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_DualToneQSSystem/AOSPModsDualToneQSSystem.apk': I/O error
2023-03-24 23:30:01.259 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_AndroidOverlayRemoveNavBar/AndroidOverlayRemoveNavBar.apk': I/O error
2023-03-24 23:30:01.259 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_DualToneQSSystem/AOSPModsDualToneQSSystem.apk': I/O error
2023-03-24 23:30:01.259 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_AndroidOverlayRemoveNavBar/AndroidOverlayRemoveNavBar.apk': I/O error
2023-03-24 23:30:01.260 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_DualToneQSSystem/AOSPModsDualToneQSSystem.apk': I/O error
2023-03-24 23:30:01.261 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_AndroidOverlayRemoveNavBar/AndroidOverlayRemoveNavBar.apk': I/O error
2023-03-24 23:30:01.261 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_DualToneQSSystem/AOSPModsDualToneQSSystem.apk': I/O error
2023-03-24 23:30:01.262 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_AndroidOverlayRemoveNavBar/AndroidOverlayRemoveNavBar.apk': I/O error
2023-03-24 23:30:01.263 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_DualToneQSSystem/AOSPModsDualToneQSSystem.apk': I/O error
2023-03-24 23:30:01.263 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_AndroidOverlayRemoveNavBar/AndroidOverlayRemoveNavBar.apk': I/O error
2023-03-24 23:30:01.264 26059-27293 .gms.persistent         com.google.android.gms.persistent    E  Failed to open APK '/product/overlay/AOSPMods_DualToneQSSystem/AOSPModsDualToneQSSystem.apk': I/O error

**Comment by TheColin21** [comment] 2023-03-24 17:33
I am having a similar Problem on my raven running the current stable stock ROM (March 2023) with Magisk 25.2: 
`03-24 18:30:06.138 15234 15234 W ziparchive: Unable to open '/product/overlay/AOSPMods_AndroidOverlayRemoveNavBar/AndroidOverlayRemoveNavBar.apk': No such file or directory
03-24 18:30:06.138 15234 15234 E napchat.android: Failed to open APK '/product/overlay/AOSPMods_AndroidOverlayRemoveNavBar/AndroidOverlayRemoveNavBar.apk': I/O error
03-24 18:30:06.139 15234 15234 W ResourcesManager: failed to preload asset path '/product/overlay/AOSPMods_AndroidOverlayRemoveNavBar/AndroidOverlayRemoveNavBar.apk'
03-24 18:30:06.139 15234 15234 W ResourcesManager: java.io.IOException: Failed to load asset path /data/resource-cache/product@overlay@AOSPMods_AndroidOverlayRemoveNavBar@AndroidOverlayRemoveNavBar.apk@idmap`

**Comment by EleoXDA** [comment] 2023-03-24 18:08
You forgot to provide logs. We can't say what happens from reading a portion of logs. @TheColin21 and @huajijam both of you extract logs zip by going to logs tab of LSposed and click "save" button on top. Then share the created zip

**Comment by huajijam** [comment] 2023-03-24 18:11
> You forgot to provide logs. We can't say what happens from reading a portion of logs. @TheColin21 and @huajijam both of you extract logs zip by going to logs tab of LSposed and click "save" button on top. Then share the created zip 

lsposed cannot capture this bug
bcz it came from gms service,
use adb logcat and set level to error,u will get a log of them,full of them in Android studio logcat

**Comment by TheColin21** [comment] 2023-03-24 18:15
> You forgot to provide logs. We can't say what happens from reading a portion of logs. @TheColin21 and @huajijam both of you extract logs zip by going to logs tab of LSposed and click "save" button on top. Then share the created zip

here they are https://clnp.cloud/s/zHokZmEfNxinoqr


> lsposed cannot capture this bug bcz it came from a system service, use adb logcat and set level to error,u will get a log of them,full of them in Android studio logcat screen

the lines I pasted up above are included in the LSPosed log so it seems that it does capture at least the same amount of data that adb logcat does.

**Comment by EleoXDA** [comment] 2023-03-24 19:13
> lsposed cannot capture this bug
> bcz it came from a system service,
> use adb logcat and set level to error,u will get a log of them,full of them in Android studio logcat screen

It does capture it. You probably don't know what LSposed logs contain. Please do share it for us to observe what is going on

**Comment by huajijam** [comment] 2023-03-26 12:30
> > lsposed cannot capture this bug
> > bcz it came from a system service,
> > use adb logcat and set level to error,u will get a log of them,full of them in Android studio logcat screen
> 
> It does capture it. You probably don't know what LSposed logs contain. Please do share it for us to observe what is going on

log here
[Uploading LSPosed_2023-03-26T20_24_53.606541.zip…]()

**Comment by EleoXDA** [comment] 2023-03-26 13:33
@huajijam I received email about your reply but do not see it in GitHub. Could you repost it?

**Comment by huajijam** [comment] 2023-03-26 14:01
> @huajijam I received email about your reply but do not see it in GitHub. Could you repost it?

[LSPosed_2023-03-26T20_24_53.606541.zip](https://github.com/siavash79/AOSPMods/files/11071762/LSPosed_2023-03-26T20_24_53.606541.zip)
here u r

**Comment by EleoXDA** [comment] 2023-03-26 15:37
> here u r 

Thanks for sharing. We could notice some trends. Will be investigated.

On the other hand, we found even more crucial errors while checking your logs. You might need to check them out as well (not related to the bug report you provided)

**Comment by Tenun-negi** [comment] 2023-04-16 15:39
> 

Universal safetynet fix moment, similar thing also happened on hided root apps by Shamiko or Magiskhide. Pain for using overlay.

**Comment by EleoXDA** [comment] 2023-04-16 19:28
> > 
> 
> Universal safetynet fix moment, similar thing also happened on hided root apps by Shamiko or Magiskhide. Pain for using overlay.

Ah so it is related to safetynet fix magisk module?

**Comment by Tenun-negi** [comment] 2023-04-19 02:39
> 

Yeah, after uninstall universal safetynet fix, no log spam of gms. 
I use magisk delta now because HuskyDG provide alternative way to pass safetynet. This way need magiskhide but no log spam for gms persistent

**Comment by EleoXDA** [comment] 2023-04-19 05:51
Great. Thanks

**Closed** 2023-04-19 05:51 UTC

**Comment by TheColin21** [comment] 2023-04-19 06:57
I find it overly optimistic to close the issue just because it does not appear using a non standard Magisk version. Reality is, that most rooted users are using Magisk with USNF.

**Comment by huajijam** [comment] 2023-04-19 07:41
this issue should be a bug by the mod
using a non standard Magisk version won't fix it,the bug is still here,but just not been triggerd

for me, putting a ton of APKs into the system app is where the real problem lies

**Comment by EleoXDA** [comment] 2023-04-19 09:45
> I find it overly optimistic to close the issue just because it does not appear using a non standard Magisk version. Reality is, that most rooted users are using Magisk with USNF.

If the problem rises when using USNF, did you check why it doesn't happen without it?

**Comment by TheColin21** [comment] 2023-04-19 10:25
I did not. I don't think that's the responsibility of the person reporting the bug though. That person is responsible for providing information on how to reproduce the bug, if possible, and provide logs.

The maintainer who gets the report should diagnose the error and fix it, if necessary (which I personally would say it is, considering it happens in one of the most common configurations (if not the most common one) that there is for this app.

**Comment by EleoXDA** [comment] 2023-04-19 13:46
> I did not. I don't think that's the responsibility of the person reporting the bug though. That person is responsible for providing information on how to reproduce the bug, if possible, and provide logs.
> 
> The maintainer who gets the report should diagnose the error and fix it, if necessary (which I personally would say it is, considering it happens in one of the most common configurations (if not the most common one) that there is for this app.

I respectfully disagree. This is firstly, an open source app. Everyone is welcome to introduce any fix if they can think of. For that reason there is pull request function. This is not only maintainers or devs job alone.

Secondly, if the issue happens due to other module, then why not first try to solve it with them?

**Comment by TheColin21** [comment] 2023-04-19 13:52
Is it already clear, which module behaves badly...or if maybe both behave correctly but trigger some third party?

Am 19. April 2023 15:46:43 MESZ schrieb Elbay Malik ***@***.***>:

**Comment by EleoXDA** [comment] 2023-04-19 16:48
It is known already
