### ISSUE TITLE
Mods reset on reopening app

### ISSUE THREAD

**Issue by swagato14** [siavash79/AOSPMods#11] opened 2022-03-31 05:49 UTC
**Describe the bug**
After I apply the mods and exit the app, if I reopen the app, all the mods are reset. There's no problem if the app is not opened again after applying mods.

**Expected behavior**
The applied mods should remain.

 - Device: Realme 3
 - OS: ArrowOS (A12)

**LSPosed Log**
[LSPosed_2022-03-31T11_11_28.585.zip](https://github.com/siavash79/AOSPMods/files/8386350/LSPosed_2022-03-31T11_11_28.585.zip)

**Comment by n3rd3x3** [comment] 2022-03-31 13:28
I believe this is a duplicate of #10

**Closed** 2022-03-31 14:50 UTC
Labels: bug, duplicate, fixed
