### ISSUE TITLE
[Bug] Not showing locked/unlocked icon bg even if remove bg is turned off

### ISSUE THREAD

**Issue by Subarupan** [siavash79/AOSPMods#491] opened 2022-12-15 20:04 UTC
### Describe the issue

Icon bg for locked/unlocked not showing

### Steps to reproduce

1. Install AOSPMods without changing any settings
2. Lockscreen icon bg won't work for lock/unlock icons
![IMAGE 2022-12-16 4:02:16 AM](https://user-images.githubusercontent.com/62179261/207955866-72c1e059-2c5b-457e-a574-97a1f466009b.jpg)

### Expected bahavior

Showing unlock/locked icon bg

### Your device setup (Please take some time to give correct information here)

Pixel 6&7 Dec update
Magisk 25.2
LSPosed 1.8.5 AOSPMods canary-186
![IMAGE 2022-12-16 4:04:12 AM](https://user-images.githubusercontent.com/62179261/207956158-b85ac00a-bd6f-4f3a-8efd-6a008c8168ee.jpg)
![IMAGE 2022-12-16 4:04:15 AM](https://user-images.githubusercontent.com/62179261/207956169-ffb147bd-3e53-4ddb-bf58-c9f160526141.jpg)
![IMAGE 2022-12-16 4:04:17 AM](https://user-images.githubusercontent.com/62179261/207956178-ef751afa-0e0b-4e74-bb41-ebc588ed7564.jpg)

**Comment by EleoXDA** [comment] 2022-12-15 20:52
Duplicate of https://github.com/siavash79/AOSPMods/issues/482

Please add it to the end of that post.

**Closed by EleoXDA** 2022-12-15 20:52 UTC
