### ISSUE TITLE
Google Sans font breaks other fonts visibility 

### ISSUE THREAD

**Issue by xslvrxslwt** [siavash79/AOSPMods#155] opened 2022-05-14 10:10 UTC
**Describe the bug**
Using `Force Google Sans font system wide` breaks the system fonts thingy that's supposed to handle ᵗᵉˣᵗ ˡᶦᵏᵉ ᵗʰᶦˢ

**To Reproduce**
1. Go to 'AOSP Mods' -> 'Theming' -> 'Force Google Sans font system wide' (enable)
2. Use any of those 'fancy' fonts
3. Squares 

**Expected behavior**
Android system is supposed to handle those

**Screenshots**
![Screenshot_20220514-120908_Kiwi Browser~2](https://user-images.githubusercontent.com/105242066/168421333-bb83337e-2398-4619-a4de-854205df6bdf.png)

 - Device: Poco X3 NFC
 - OS: Arrow OS | Android 12.1

**Comment by EleoXDA** [comment] 2022-05-14 15:40
It is a custom font. It is meant to be used in standard usage. I have my own custom font and even that doesn't handle your text normally. See screenshot.

![Screenshot_20220514-173638.png](https://user-images.githubusercontent.com/27622683/168438815-dd04b890-ed63-4f3a-80b7-6fb893fe170b.png)

P.S. You need to restart after selecting custom fonts, and then restart after enabling Google Sans.

BTW if you can find a Google Sans font that includes all characters in shared font + the upper lower and etc characters that you use in standard usage, you can share it so that dev can put it into the module :) you can also use a magisk flashable zip to add your own custom font like myself. If you are interested I can share it with all the guidance

**Comment by xslvrxslwt** [comment] 2022-05-14 16:16
Google Sans font is the only one that breaks other characters, fonts like Linotte, Comic Sans, etc. are displaying that text properly 😁

**Comment by EleoXDA** [comment] 2022-05-14 16:21
> Google Sans font is the only one that breaks other characters, fonts like Linotte, Comic Sans, etc. are displaying that text properly 😁
> 
> btw. yours is what it is supposed to look like, not squares like in my case :'D

Don't you see the capital "I"s instead of standard "i"s? I think that means it cannot correctly show.

But anyways,

As I said, Google Sans package included in the module may not be complete for your usage. If you can find the font package that includes your type of texts too, please share.

And even if you want to install font separately from this module, as I replied above, it is also possible. And very easy. 

I personally don't like Google Sans font per se, so I cannot be hr judge here

**Comment by mingaldrichgan** [comment] 2022-05-14 16:31
Google Sans also doesn't display Italics correctly in the Gmail app, FWIW.

**Comment by siavash79** [comment] 2022-05-20 00:48
I think you're right. If it doesn't work well for you, disable it and reboot two times

**Comment by xslvrxslwt** [comment] 2022-05-20 11:01
> I think you're right. If it doesn't work well for you, disable it and reboot two times

Rebooting won't fix the issues with this font and this font only.



> > Google Sans font is the only one that breaks other characters, fonts like Linotte, Comic Sans, etc. are displaying that text properly 😁
> > btw. yours is what it is supposed to look like, not squares like in my case :'D
> 
> Don't you see the capital "I"s instead of standard "i"s? I think that means it cannot correctly show.
> 
> But anyways,
> 
> As I said, Google Sans package included in the module may not be complete for your usage. If you can find the font package that includes your type of texts too, please share.
> 
> And even if you want to install font separately from this module, as I replied above, it is also possible. And very easy.
> 
> I personally don't like Google Sans font per se, so I cannot be hr judge here

Ugh, I'm using the default font now (no AOSP mods) and it's exactly same as urs so I see no problems there..

**Comment by zxw660404** [comment] 2022-05-24 03:22
I like Google sans font. Is there a module that only forces Google sans font system scope (enabled)

**Comment by EleoXDA** [comment] 2022-05-24 05:30
If you have the font ttf file (or you can download it from internet) I can give you a magisk module to do that. All you would need to do is to replace the Regular.ttf inside that package (read the font description below) to the one that you have and voila! Currently it has another font inside, called Banjax Notched Bold.

**Font Changer Magisk Module**
[Font Changer - Banjax Notched Bold.zip](https://github.com/siavash79/AOSPMods/files/8759767/Font.Changer.-.Banjax.Notched.Bold.zip)

This is the font changer module that I have been using. All you need to do is to install MT Manager app, create a duplicate of the zip, copy the font file into the "fonts" folder, delete the "Regular.ttf" that is present in that folder. Then rename "your ttf" file to "Regular.ttf". After finishing editing, don't forget to rename the duplicate zip with the font name that is present inside the zip. The reason is, because you rename the font file to Regular.ttf, you will not be able to see what font you have inside without flashing it and checking the font that is applied.

Also, if you are using the AOSPMods magisk module, be sure to:
- Disable "using custom fonts" in themes
- Reboot
- Flash font changer magisk module
- Reboot

Also, if there is any other font changer module, be sure to disable them before flashing this module in magisk.

**Comment by mld9401** [comment] 2022-05-24 09:59
> If you have the font ttf file (or you can download it from internet) I can give you a magisk module to do that. All you would need to do is to replace the Regular.ttf inside that package (read the font description below) to the one that you have and voila! Currently it has another font inside, called Banjax Notched Bold.
> 
> **Font Changer Magisk Module**
> [Font Changer - Banjax Notched Bold.zip](https://github.com/siavash79/AOSPMods/files/8759767/Font.Changer.-.Banjax.Notched.Bold.zip)
> 
> This is the font changer module that I have been using. All you need to do is to create a duplicate of the zip, copy the font file into the "fonts" folder, delete the "Regular.ttf" that is present in that folder. Then rename "your ttf" file to "Regular.ttf". After finishing editing, don't forget to rename the duplicate zip with the font name that is present inside the zip. The reason is, because you rename the font file to Regular.ttf, you will not be able to see what font you have inside without flashing it and checking the font that is applied. If you are using Windows, use 7-Zip; in android it is advised to use MT Manager app. The reason is because these applications do not change zip attributes and even after editing zip, the files are flashable in magisk. When using other apps, after editing zip you may find that they are corrupted and not able to be flashed in magisk.
> 
> Also, if you are using the AOSPMods magisk module, be sure to:
> - Disable "using custom fonts" in themes
> - Reboot twice.
> - Flash font changer magisk module
> - Reboot
> 
> Also, if there is any other font changer module, be sure to disable them before flashing this module in magisk.

I have tried your solution with GoogleProductSansFont and it worked, but unfortunatly bold font on Gmail doesn't work.

**Closed** 2022-05-26 18:11 UTC
Labels: bug, wontfix
