### ISSUE TITLE
[Bug] Expanded notification shade bottom buttons have light background instead of dark

### ISSUE THREAD

**Issue by dazewell** [siavash79/AOSPMods#356] opened 2022-09-19 03:09 UTC
### Describe the issue

When you expand the notification shade, the bottom buttons (VPN monitoring warning; currently active apps button) turn white while they should be black

### Steps to reproduce

1. **Make sure you're on the light theme**
1. Install LSPosed, reboot
2. Install AOSPMods, reboot
3. Open AOSPMods, grant root access, reboot
1. Long tap on the home screen
4. Wallpaper & style
5. Change the system Monet color to a different one than it is right now. Or change the wallpaper while "Wallpaper Colors" is enabled.
6. Expand notification shade.
7. Notice the bottom buttons have white background while the Setting button is okay and has a dark background.

Attaching the same steps before installing AOSPMods and then the same steps after installing AOSPMods.
* Before installing:
  ![Before installing AOSPMods](https://user-images.githubusercontent.com/12871617/190942581-b818ee54-27de-4211-88e2-abe888c5e11e.jpg)
* After installing:
  ![After installing AOSPMods](https://user-images.githubusercontent.com/12871617/190942592-ffd18c85-29fc-4b17-9de3-63568c3528fc.jpg)

### Expected bahavior

The bottom buttons in the notification shade have dark background (similar to the Settings button in the same row).

### Your device setup (Please take some time to give correct information here)

* Google Pixel 6 
* Android 13 Stable `TP1A.220905.004`
* September 5, 2022
* 25.2 (25200)
* ![Screenshot_20220918-195839](https://user-images.githubusercontent.com/12871617/190943186-64b13c55-560c-4176-809d-fafbbaddb284.png)
* ![Screenshot_20220918-200307](https://user-images.githubusercontent.com/12871617/190943423-804a4d29-ff85-42b1-8901-503761947129.png)
* 1.8.4 (6609) Zygisk
* ![Screenshot_20220918-200429](https://user-images.githubusercontent.com/12871617/190943490-4f539fd8-37b6-4de0-b4f2-46046a36a814.png)
* No setting backup because it happens when NO settings are even enabled.

### Logs

[LSPosed_2022-09-18T20_08_42.241540.zip](https://github.com/siavash79/AOSPMods/files/9595955/LSPosed_2022-09-18T20_08_42.241540.zip)

**Comment by bzz11g** [comment] 2022-09-19 09:06
Hi there,
I can confirm this bug
![Screenshot_20220919-104125](https://user-images.githubusercontent.com/1549909/190977018-a77fb03a-ff16-47e6-9e68-e3748b011ccc.png)
Without AOSPmods all working fine
![Screenshot_20220919-112315](https://user-images.githubusercontent.com/1549909/190984490-d91fc96d-e88f-44b8-a17d-9378331c7bd3.png)

- Google Pixel 6
- Android 13 Stable TP1A.220905.004
- September 5, 2022
- Magisk 25.2 (25200) Zygisk
- LSPosed 1.8.4 (6609) Zygisk
- AOSPmods: canary-139

My Magisk and LSposed modules list
![Screenshot_20220919-114536](https://user-images.githubusercontent.com/1549909/190984024-be84a34a-dcf8-477d-aab7-76d8cf053cff.png)
AOSPmods settings export (just unzip): 
[AOSPMODS_settings_export.zip](https://github.com/siavash79/AOSPMods/files/9597480/AOSPMODS_settings_export.zip)
LSPosed logs:
[verbose_LSPosed_2022-09-19T11_57_19.116707.zip](https://github.com/siavash79/AOSPMods/files/9597485/verbose_LSPosed_2022-09-19T11_57_19.116707.zip)
Magisk logs
[magisk_log_2022-09-19T11.57.00.log](https://github.com/siavash79/AOSPMods/files/9597491/magisk_log_2022-09-19T11.57.00.log)

**Comment by dazewell** [comment] 2022-09-19 21:36
> Can you check whether issue persists when you enable following option: AOSPMods/Quick Settings/Apply light QS Panel using light theme

I couldn't reproduce this exact problem, but this flag brings other issues from time to time:
* Notice the clock and date in different colors:
  ![Screenshot_20220919-143000](https://user-images.githubusercontent.com/12871617/191123805-2cd613a8-9a2e-4ac6-a703-04a58b5d6f08.png)
* The panel with the buttons at the bottom is weird - rounding is wrong and the color is full black for some reason.
  ![Screenshot_20220919-143339](https://user-images.githubusercontent.com/12871617/191123814-b6a95c08-1dbc-4e12-bb42-7fd9a91d2642.png)

**Comment by erenmete** [comment] 2022-09-20 05:31
> Can you check whether issue persists when you enable following option: AOSPMods/Quick Settings/Apply light QS Panel using light theme

Applying the light QS makes the UI glitched and switching back to dark after doesn't solve the issue. The UI when applying the light QS wasn't glitched out before, maybe it is a ROM issue but when it wasn't glitched, the issue was gone in light QS but still there in dark QS.

This is after applying the light QS:

![Screenshot_20220920-082747_AOSP_Mods](https://user-images.githubusercontent.com/58091473/191174946-b19f488b-edca-43ae-b95e-5ba0cb58b941.png)

This is after restarting SystemUI:

![Screenshot_20220920-082805_AOSP_Mods](https://user-images.githubusercontent.com/58091473/191174994-e8539ca8-9fe0-418f-b3ec-7dd4687fae34.png)

This is after switching back to dark and restarting the SystemUI:

![Screenshot_20220920-082957_AOSP_Mods](https://user-images.githubusercontent.com/58091473/191175055-7a978c03-c8dd-4e20-a2b6-33ddc642d369.png)

**Comment by EleoXDA** [comment] 2022-09-20 07:08
> > Can you check whether issue persists when you enable following option: AOSPMods/Quick Settings/Apply light QS Panel using light theme
> 
> Applying the light QS makes the UI glitched and switching back to dark after doesn't solve the issue. The UI when applying the light QS wasn't glitched out before, maybe it is a ROM issue but when it wasn't glitched, the issue was gone in light QS but still there in dark QS.
> 
> This is after applying the light QS:
> 
> ![Screenshot_20220920-082747_AOSP_Mods](https://user-images.githubusercontent.com/58091473/191174946-b19f488b-edca-43ae-b95e-5ba0cb58b941.png)
> 
> This is after restarting SystemUI:
> 
> ![Screenshot_20220920-082805_AOSP_Mods](https://user-images.githubusercontent.com/58091473/191174994-e8539ca8-9fe0-418f-b3ec-7dd4687fae34.png)
> 
> This is after switching back to dark and restarting the SystemUI:
> 
> ![Screenshot_20220920-082957_AOSP_Mods](https://user-images.githubusercontent.com/58091473/191175055-7a978c03-c8dd-4e20-a2b6-33ddc642d369.png)

which device? ROM? Android version?

**Comment by EleoXDA** [comment] 2022-09-20 07:10
> > Can you check whether issue persists when you enable following option: AOSPMods/Quick Settings/Apply light QS Panel using light theme
> 
> I couldn't reproduce this exact problem, but this flag brings other issues from time to time:
> * Notice the clock and date in different colors:
>   ![Screenshot_20220919-143000](https://user-images.githubusercontent.com/12871617/191123805-2cd613a8-9a2e-4ac6-a703-04a58b5d6f08.png)
> * The panel with the buttons at the bottom is weird - rounding is wrong and the color is full black for some reason.
>   ![Screenshot_20220919-143339](https://user-images.githubusercontent.com/12871617/191123814-b6a95c08-1dbc-4e12-bb42-7fd9a91d2642.png)
> 

See mine with and without "Enable dual tone QS panel" option:
![IMG_20220920_090913.jpg](https://user-images.githubusercontent.com/27622683/191190818-7680ee0c-4e8e-4725-a205-ef1fed30de26.jpg)
![IMG_20220920_090931.jpg](https://user-images.githubusercontent.com/27622683/191190843-c0f002f3-50c9-472d-8d2a-6dafb1a67844.jpg)

Your devices are acting weird. And I am tempted to know why...

**Comment by erenmete** [comment] 2022-09-20 07:11
> 

Poco F3, Evolution X Android 13. For me the light QS isn't a big deal since i don't use it. It's just the bottom buttons that have light theme on dark QS.

**Comment by EleoXDA** [comment] 2022-09-20 07:13
> > 
> 
> Poco F3, Evolution X Android 13. For me the light QS isn't a big deal since i don't use it. It's just the bottom buttons that have light theme on dark QS.

Evolution X is not a supported ROM. You already have many tweaks in Evolution X and the source code is changed too much in Evo with respect to AOSP code. It is not possible to support it unless you only support Evo (which already contains modifications)

**Comment by erenmete** [comment] 2022-09-20 07:17
> > > 
> > 
> > 
> > Poco F3, Evolution X Android 13. For me the light QS isn't a big deal since i don't use it. It's just the bottom buttons that have light theme on dark QS.
> 
> Evolution X is not a supported ROM. You already have many tweaks in Evolution X and the source code is changed too much in Evo with respect to AOSP code. It is not possible to support it unless you only support Evo (which already contains modifications)

I use this mod mainly for status bar height, and the only problem i seek solution for is the light theme on the bottom buttons like the owner of this thread suggests. Do you have the main issue on your system? Perhaps both the owner of the thread and I are using unsupported ROMs and that's why. If so, I guess I'll have to change ROMs

**Comment by EleoXDA** [comment] 2022-09-20 07:45
> > > > 
> > > 
> > > 
> > > Poco F3, Evolution X Android 13. For me the light QS isn't a big deal since i don't use it. It's just the bottom buttons that have light theme on dark QS.
> > 
> > 
> > Evolution X is not a supported ROM. You already have many tweaks in Evolution X and the source code is changed too much in Evo with respect to AOSP code. It is not possible to support it unless you only support Evo (which already contains modifications)
> 
> I use this mod mainly for status bar height, and the only problem i seek solution for is the light theme on the bottom buttons like the owner of this thread suggests. Do you have this main issue on your system? Perhaps both the owner of the thread and I are using unsupported ROMs and that's why. If so, I guess I'll have to change ROMs. Although I just realized that the thread owner is using stock and still having this issue.

Yes, as I replied, he has some issues that we cannot replicate. But your light theme is not what we both can observe. So, maybe if we find what is causing issue on the OP, it can also be applied to you. But there is a strong probability that it will not affect you. So, just that you know.

**Comment by bzz11g** [comment] 2022-09-21 08:48
> Can you check whether issue persists when you enable following option: AOSPMods/Quick Settings/Apply light QS Panel using light theme

yes, the problem does not occur if you use a light notification theme with light system theme
and no issues with dark theme with switch "Apply light QS Panel using light theme" activated
![Screenshot_20220921-114223](https://user-images.githubusercontent.com/1549909/191459565-380370e3-173a-4220-9f30-d6fae87c9c0c.png)

**Comment by dazewell** [comment] 2022-09-21 18:48
Is this an option to move the two settings related to the white BG of the notification shade to the Magisk package leaving the Xposed one without it? Or build a test package without this feature so I could test and confirm it is related or not?

**Comment by dazewell** [comment] 2022-09-22 02:46
One another thing to mention, and I've updated the repro steps, is to do ot on the light theme. Please, try again.

I've just tried to disable all modules besides LSPosed and AOSPMods - no luck. It is still happening.

**Comment by dazewell** [comment] 2022-09-22 04:38
Well, I've built a version w/o both the light QA and dual tone QS settings (and removed respective controllers) - all is working fine. So, the problem is somewhere in those overlays or hooks. I'm not too familiar with all the stuff, I just wanted to have proof that this is what causes the problems. I hope this can help somehow. I could've attached a resulting zip here if needed.

**Comment by bzz11g** [comment] 2022-09-22 04:59
> I could've attached a resulting zip here if needed.

 Share please, I will also check on my device

**Comment by dazewell** [comment] 2022-09-22 05:55
**DISCLAIMER**: I'm not responsible for any harm this file can do to your device, even though I simply removed several lines of code and built it locally.

[AOSPMods_Xposed.zip](https://github.com/siavash79/AOSPMods/files/9622634/AOSPMods_Xposed.zip)

_Full version cannot be attached due to GH limits._

**Comment by dazewell** [comment] 2022-09-22 22:55
> This fixes the issue, can you do the full version too?
I can, but cannot attach it to GitHub. Ping me in the telegram support group, I can put it there I think.

**Comment by EleoXDA** [comment] 2022-09-23 06:08
> Well, I've built a version w/o both the light QA and dual tone QS settings (and removed respective controllers) - all is working fine. So, the problem is somewhere in those overlays or hooks. I'm not too familiar with all the stuff, I just wanted to have proof that this is what causes the problems. I hope this can help somehow. I could've attached a resulting zip here if needed.

The only problem is with the standard light theme on my device. The light light theme is working fine. The dark theme works fine. But the standard light theme (with black qs bg and white notification bg) is faulty.

It was my advice to Siavash to remove the possibility of a standard light theme, because it looks very odd. Then the themes work fine and colors work ok as far as I have tested. The white and black clock color gets reset back to normal after a systemUI restart. And that black bar in bottom is only because of "standard theme". If you use repainter with amoled black bg or pitch black theme in AOSPMods that bar is invisible

**Comment by EleoXDA** [comment] 2022-09-23 17:40
Is this duplicate of this bugreport?
https://github.com/siavash79/AOSPMods/issues/336

**Comment by dazewell** [comment] 2022-09-23 17:43
> Is this duplicate of this bugreport? #336

It is, yes, but for some reason, @siavash79 has asked not to close it but just create a new one. It is fine I think if we close it and just keep a link to it.

**Comment by EleoXDA** [comment] 2022-09-23 19:19
No problem, let's let Siavash read it

**Comment by siavash79** [comment] 2022-09-24 08:28
Expect the fix in canary 139

**Closed** 2022-09-24 08:28 UTC
