### ISSUE TITLE
Enabling light QS panel causes systemUI to restart/crash every time the device is locked/the screen is turned off

### ISSUE THREAD

**Issue by Jnss98b** [siavash79/AOSPMods#151] opened 2022-05-12 20:33 UTC
**Describe the bug**
What the title says. Also, it doesn't matter if dual tone panel is enabled or not too. The effect is the same

**To Reproduce**
1. Enable light QS panel
2. Press the power button
3. Observe systemUI restart (more noticeable if AOD is available and enabled too)

**Screenshots**
https://user-images.githubusercontent.com/24306400/168162577-98b54500-4601-4e8b-85b0-aa8e246b0157.mp4

 - Device: Google Pixel 5 (redfin)
 - OS: Android 12.1 May 2022 Patch

**LSPosed Log**
[LSPosed_2022-05-12T13_14_07.816.zip](https://github.com/siavash79/AOSPMods/files/8682354/LSPosed_2022-05-12T13_14_07.816.zip)

**Comment by EleoXDA** [comment] 2022-05-14 15:45
Hello. I am using exactly the same module with pixel stock firmware and have none of what you have with or without AOD. And all the testers in the group don't have it either.

I noticed you have lots of errors in aospmods.apk in your logs. This could be a clash between other magisk and/or lsposed modules. What other modules do you have running?

**Comment by Jnss98b** [comment] 2022-05-14 18:24
@EleoXDA 
![Screenshot_20220514-112344](https://user-images.githubusercontent.com/24306400/168443971-68181c72-9b8d-43bc-a5f9-1f790eb19238.png)

**Comment by EleoXDA** [comment] 2022-05-14 18:41
> @EleoXDA 
> ![Screenshot_20220514-112344](https://user-images.githubusercontent.com/24306400/168443971-68181c72-9b8d-43bc-a5f9-1f790eb19238.png)
> 

Please share lsposed modules too. I am guessing you are running Magisk canary, right?

To check the module incompatibility, disable all modules in magisk and lsposed, other than:
-aospsmods
- magiskhide props
- zygisk lsposed

and restart. Check and write your observations.

As I said I am also on android 12.1 May security patch and I have not observed what you describe.

**Comment by Jnss98b** [comment] 2022-05-14 19:07
@EleoXDA No I've never used anything other than stable magisk. Also I edited the post 5 second after with that lsposed modules screenshot.

![Screenshot_20220514-120627](https://user-images.githubusercontent.com/24306400/168445191-1a497a49-bda8-4fcc-bb68-5ce14bcceaed.png)

**Comment by EleoXDA** [comment] 2022-05-14 19:09
Well, switch to canary magisk first things first

**Comment by Jnss98b** [comment] 2022-05-14 19:13
Why should I do that? What's currently in canary that would help? I don't really feel comfortable running the most unstable version of magisk

**Comment by Jnss98b** [comment] 2022-05-14 22:37
@EleoXDA Absolutely nothing changed. SystemUI still crashes as usual

https://user-images.githubusercontent.com/24306400/168450204-ac9ccef8-f06b-4951-aae8-a50aac4506f3.mp4

**Comment by EleoXDA** [comment] 2022-05-14 23:01
> Why should I do that? What's currently in canary that would help? I don't really feel comfortable running the most unstable version of magisk

You should switch to canary to get support in android 12L. Switch to canary, check and report back

**Comment by EleoXDA** [comment] 2022-05-15 19:31
> @EleoXDA Absolutely nothing changed. SystemUI still crashes as usual
> 
>  ezgif.com-gif-maker.1.mp4

What have you tried so far?
- Disabling the modules other than 3
- Switching to canary Magisk

This will make your phone exactly same setup as mine, If you still fail then you need to revert all the data of AOSPMods apk and redo every mod one by one to find which one actually is the culprit.

Other than this we cannot help you as there are numerous users with exactly same setup as you and me and have no issues that you observe.

I will wait for one last response from you about this issue

**Comment by Jnss98b** [comment] 2022-05-15 19:46
> > @EleoXDA Absolutely nothing changed. SystemUI still crashes as usual
> > ezgif.com-gif-maker.1.mp4
> 
> What have you tried so far?
> 
> * Disabling the modules other than 3
> * Switching to canary Magisk

The former, just watch the screen recording man

> This will make your phone exactly same setup as mine, If you still fail then you need to revert all the data of AOSPMods apk and redo every mod one by one to find which one actually is the culprit.

Light QS panel is the culprit. I literally did just that before filing a bug report

> Other than this we cannot help you as there are numerous users with exactly same setup as you and me and have no issues that you observe.

Then maybe you should let @siavash79 deal with this. Maybe he could get some clue from the whole verbose lsposed log I included. It's very normal for bugs to show up just for some even with similar setups because there's just so many variables to account for. Not to mention like I said earlier, I have done my own testing and isolated the cause down to that light QS setting so it must have been conflicting with something.

> BTW You say you ger systemUI restart, but do you actually observe it in running logs or do you "assume" there is a systemUI restart?
Educated guess because the widgets on pixel launcher reload every time and the notification shade as well. Not to mention the whole lock screen flashed and reloaded UI elements like you saw in the screen recording. If you don't think that's a sign of systemUI crash idk what to tell you

**Comment by EleoXDA** [comment] 2022-05-15 20:09
I do understand that you are irritated with the fact that the person who deals with you is not the dev itself, but I just want to make sure that everything is narrow to the point

When you first reported:
1. Even though you are on android 12L you are still not on magisk canary but on stable. You must switch to the canary build.
2. You had other modules enabled, which introduces the background noise and possible clashes with this module.

And even though you have done (or didn't even bother to do) these changes above, you still haven't updated your LSposed logs.

Either case, until there is an update to the logs accordingly with magisk canary and removing all the other modules, I would advise @siavash79 to keep this issue on hold.

My work here is done.
I hope you have good luck in future endeavors on this issue. I tried my best to help you but you apparently don't need any help with this issue.
Cheers.

**Comment by Jnss98b** [comment] 2022-05-15 20:35
I'd rather wait until whatever android 12L support hit magisk stable to deal with this. Reverting from magisk canary to stable is a pain in the ass and I don't have time for that. I get you wanted to narrow the cause down but I really really doubt updating to magisk canary changes much considering android 12L is a minor update despite the API bump and the fact that this module mostly modifies systemUI through xposed/lsposed anyway

**Comment by bzz11g** [comment] 2022-05-25 06:29
Hi There!
I can confirm that something wrong with Light QS theme
My setup:
**Pixel 6 SP2A.220505.002 Android 12.1 May Update
Magisk version 24306 (Canary)
LSPosed v1.8.3 (6552) Zygisk
Repainter 1.2.4 installed and activated**
List of installed Magisk modules:
![Screenshot_20220525-090700](https://user-images.githubusercontent.com/1549909/170192177-bc1cd605-b357-4968-89c5-9bde020c85e3.png)
List of installed Xposed modules:
![Screenshot_20220525-091056](https://user-images.githubusercontent.com/1549909/170192295-a466002c-2325-47bc-ab82-296318b6749c.png)

Behavior when enabled Light QS theme:
you can see double flickering on AOD screen, and additional flicker after unlock
https://imgur.com/Qbs2LUG

Behavior when enabled Light QS theme:
no flickering
https://imgur.com/a/nXwhlRh

My Magisk an LSPosed logs:
[LSPosed_2022-05-25T09_26_48.914.zip](https://github.com/siavash79/AOSPMods/files/8768461/LSPosed_2022-05-25T09_26_48.914.zip)
[magisk_log_2022-05-25T09_26_36.log](https://github.com/siavash79/AOSPMods/files/8768462/magisk_log_2022-05-25T09_26_36.log)
[LSPosed_2022-05-25T09_26_58.815.zip](https://github.com/siavash79/AOSPMods/files/8768463/LSPosed_2022-05-25T09_26_58.815.zip)

I hope this will be helpful
Best regrets

**Comment by bzz11g** [comment] 2022-05-25 07:14
_> Why do you need Pixelify GPhotos if you have Google Pixel device?_
Unlimited Google Photo Storage in original quality ;)
_> Also, try disable repainter, reboot and retry_
All the same
[magisk_log_2022-05-25T10_11_22.log](https://github.com/siavash79/AOSPMods/files/8768778/magisk_log_2022-05-25T10_11_22.log)
[Module_LSPosed_2022-05-25T10_11_47.272.zip](https://github.com/siavash79/AOSPMods/files/8768779/Module_LSPosed_2022-05-25T10_11_47.272.zip)
[Verbose_LSPosed_2022-05-25T10_12_04.598.zip](https://github.com/siavash79/AOSPMods/files/8768780/Verbose_LSPosed_2022-05-25T10_12_04.598.zip)

**Comment by EleoXDA** [comment] 2022-05-25 07:22
> _> Why do you need Pixelify GPhotos if you have Google Pixel device?_ Unlimited Google Photo Storage in original quality ;) _> Also, try disable repainter, reboot and retry_ All the same [magisk_log_2022-05-25T10_11_22.log](https://github.com/siavash79/AOSPMods/files/8768778/magisk_log_2022-05-25T10_11_22.log) [Module_LSPosed_2022-05-25T10_11_47.272.zip](https://github.com/siavash79/AOSPMods/files/8768779/Module_LSPosed_2022-05-25T10_11_47.272.zip) [Verbose_LSPosed_2022-05-25T10_12_04.598.zip](https://github.com/siavash79/AOSPMods/files/8768780/Verbose_LSPosed_2022-05-25T10_12_04.598.zip)

Repainter is still present in the logs. Please uninstall repainter, reboot and check again

**Comment by bzz11g** [comment] 2022-05-25 07:35
Still double flickering
[magisk_log_2022-05-25T10_28_07.log](https://github.com/siavash79/AOSPMods/files/8768893/magisk_log_2022-05-25T10_28_07.log)
[Verbose_LSPosed_2022-05-25T10_28_36.624.zip](https://github.com/siavash79/AOSPMods/files/8768894/Verbose_LSPosed_2022-05-25T10_28_36.624.zip)
[Modules_LSPosed_2022-05-25T10_28_18.912.zip](https://github.com/siavash79/AOSPMods/files/8768895/Modules_LSPosed_2022-05-25T10_28_18.912.zip)
Also find a bug with brightness slider
 
![Screenshot_20220525-102750](https://user-images.githubusercontent.com/1549909/170207102-b4975b2c-606f-457f-b7a4-1362f37f8f78.png)

**Comment by siavash79** [comment] 2022-05-26 18:52
Ok

First of all: I'm really sorry I'm THIS late. I honestly didn't notice the issue and didn't notice the conversation!

Anyway: I do confirm the issue. I can reproduce it on my own device too: but only in certain situations. It seems like if we unlock and lock very quickly it happens, but if some time passes it doesn't happen anymore.

One thing to be sure about: this is NOT a systemUI restart. It seems to me that this is the result of overlays getting applied and systemUI refreshes its looks one step more than it's needed. So nothing to worry about. It's just a graphical glitch and I will look into it soon.

Thanks for supporting the matter with lots of material

Cheers

**Comment by EleoXDA** [comment] 2022-05-26 18:57
> Ok
> 
> First of all: I'm really sorry I'm THIS late. I honestly didn't notice the issue and didn't notice the conversation!
> 
> Anyway: I do confirm the issue. I can reproduce it on my own device too: but only in certain situations. It seems like if we unlock and lock very quickly it happens, but if some time passes it doesn't happen anymore.
> 
> One thing to be sure about: this is NOT a systemUI restart. It seems to me that this is the result of overlays getting applied and systemUI refreshes its looks one step more than it's needed. So nothing to worry about. It's just a graphical glitch and I will look into it soon.
> 
> Thanks for supporting the matter with lots of material
> 
> Cheers

On top of that I also didn't notice the "systemUI restart" event in either my phone's logs or in logs reported above. That is why I kept it on hold to see what this will progress to

**Comment by siavash79** [comment] 2022-05-26 18:59
To add to the possible cause: light QS theme is both an Xposed mod and an Overlay. Because there's not much room to inject resources using Xposed.

The mod also looks for changes in screen and reapplies the overlays then. Otherwise it won't work

So what you see is reapplication of overlay. although we're not supposed to see it 😐

**Comment by siavash79** [comment] 2022-05-26 19:42
@bzz11g @Jnss98b
can you please try this build and let me know if it's ok? You'll need to 
- Download and install the APK without uninstalling your current module
- Restart SystemUI for the update to "apply"

https://github.com/siavash79/AOSPMods/actions/runs/2392745972

**Comment by bzz11g** [comment] 2022-05-26 19:48
> @bzz11g @Jnss98b can you please try this build and let me know if it's ok? You'll need to
> 
> * Download and install the APK without uninstalling your current module
> * Restart SystemUI for the update to "apply"
> 
> https://github.com/siavash79/AOSPMods/actions/runs/2392745972

Yes, now work good for me
Thank you👍

**Comment by Jnss98b** [comment] 2022-05-27 00:40
@siavash79 @bzz11g Is it just me or does this fixed build not retain the gesture bar material you color when you restart systemUI? This didn't happen to me before and I know for sure bc I used to restart systemUI often to fix the unthemed clock color AOSP bug mentioned in #153

**Comment by Jnss98b** [comment] 2022-05-27 00:42
Also are inactive QS toggles supposed to blend in with the background with light QS like this (the flashlight toggle in the screenshot)? I'll make a separate feature request if that were the case

![image](https://user-images.githubusercontent.com/24306400/170606147-d9b27ae2-ba94-4c4e-b2b1-c915aac1708a.png)

**Comment by siavash79** [comment] 2022-05-27 01:57
> @siavash79 @bzz11g Is it just me or does this fixed build not retain the gesture bar material you color when you restart systemUI? This didn't happen to me before and I know for sure bc I used to restart systemUI often to fix the unthemed clock color AOSP bug mentioned in #153

For some reason the dual tone light QS theme and material navigation pill are not so much good friends. I'll have to look into that sometime

**Comment by siavash79** [comment] 2022-05-27 01:58
> Also are inactive QS toggles supposed to blend in with the background with light QS like this (the flashlight toggle in the screenshot)? I'll make a separate feature request if that were the case
> 
> ![image](https://user-images.githubusercontent.com/24306400/170606147-d9b27ae2-ba94-4c4e-b2b1-c915aac1708a.png)
> 

Yes I'm aware of that. It will be fixed just in time for next release

**Comment by siavash79** [comment] 2022-05-27 04:26
This is supposed to be the final touch on light QS theme.
Please let me know if you find anything

https://github.com/siavash79/AOSPMods/actions/runs/2394528236

**Comment by Jnss98b** [comment] 2022-05-27 05:18
> This is supposed to be the final touch on light QS theme. Please let me know if you find anything
> 
> https://github.com/siavash79/AOSPMods/actions/runs/2394528236

Looks like inactive tiles color is fixed!

**Closed** 2022-05-27 06:20 UTC
Labels: bug, fixed

**Comment by Jnss98b** [comment] 2022-07-14 01:12
@siavash79 I don't know if it's just me but I'm on the latest build and this issue is happening again, but only when the device theme changes automatically while the screen is off

**Comment by Jnss98b** [comment] 2022-07-14 01:15
https://user-images.githubusercontent.com/24306400/178866019-8bc57253-3f39-46b9-9673-4bdf03043cbd.mp4

**Comment by siavash79** [comment] 2022-07-14 02:27
I watched the videos few times, and didn't observe any systemUI restart.

systemUI restart makes the whole screen go full black for 1 complete second.

What you showed is a "overlay refresh", which is intended on system theme or color change.

**Comment by Jnss98b** [comment] 2022-07-14 03:15
@siavash79 Oh yes ik it's not a systemUI restart and wasn't trying to imply that at all. We already established that above.

> To add to the possible cause: light QS theme is both an Xposed mod and an Overlay. Because there's not much room to inject resources using Xposed.
> 
> The mod also looks for changes in screen and reapplies the overlays then. Otherwise it won't work
> 
> So what you see is reapplication of overlay. although we're not supposed to see it 😐

I was just saying the bug that happened before and got fixed came back again. It still only happens with light QS but this time it doesn't happen with every screen off, only when the theme changes while the screen is off
